### ISSUE TITLE
reload from script

### ISSUE THREAD

**Issue by haras-unicorn** [sharkdp/vivid#116]
How would i reload this from a script?

**Comment by sharkdp** [comment]
Can you be more specific? I don't know what you are trying to achieve?

**Comment by haras-unicorn** [comment]
so im using a program that extracts prominent colors from a picture and id like to run vivid and apply the new style on running processes if thats possible

**Comment by sharkdp** [comment]
> and apply the new style on running processes if thats possible

I'm really not sure what you mean

**Comment by haras-unicorn** [comment]
sry i realized this is not a vivid problem but a more general problem of applying new environment to running processes

thx for trying to help anyway :)
