### ISSUE TITLE
export VIVID_THEME as a envvar so that printenv will show active theme

### ISSUE THREAD

**Issue by dewcansam** [sharkdp/vivid#140]
main.rs ln 87 states that it is setting env var VIVID_THEME . I don't see it when using `printenv`. Is this being exported ? Or would it be possible to export it so that the active theme is displayed, when using `printenv` ? This would be a big help.

**Comment by sharkdp** [comment]
> main.rs ln 87 states that it is setting env var VIVID_THEME

No. That is *reading* `VIVID_THEME`.

> I don't see it when using `printenv`. Is this being exported ?

Even if we *would* set it, you can not export an environment variable from a process to the outer shell. That is not possible.

`VIDID_THEME` is a way for users to *set* the active theme. For example, I have this in my shells RC file:
```bash
if command -v vivid &> /dev/null; then
    export VIVID_THEME="molokai"
    export LS_COLORS="$(vivid generate)"
fi
```

**Comment by dewcansam** [comment]
OK I got ya. I have it set in my rc but I still have not figured out which theme I like so I have a tendency to set it on the term, then later forget which one I set. Got to thinking well I should be able to set it myself if I need. So this is what I do now.
`export vivid_theme=dracula; export LS_COLORS="$(vivid generate $vivid_theme)";`
