### ISSUE TITLE
Vim: add .swo

### ISSUE THREAD

**Issue by yochem** [sharkdp/vivid#149]
I just noticed that *.swo files are not recognized. From the (Neo)vim help file:

```
- If this file already exists (e.g., when you are recovering from a crash) a
  warning is given and another extension is used, ".swo", ".swn", etc.
- ...

							*E326*
Technical: If the ".swp" file name already exists, the last character is
	   decremented until there is no file with that name or ".saa" is
	   reached.  In the last case, no swap file is created.
```

If you want to fully cover all swap files, you would have to add all of `.sw[a-o][a-z]` extensions. Thats probably to much for such a niche use case, but I think adding `.swo` and `.swn` is nice.

Of course I can create a PR for it, but I thought I would ask first what you think would be best.

**Comment by sharkdp** [comment]
> Of course I can create a PR for it, but I thought I would ask first what you think would be best.

Sounds good, thank you!
