### ISSUE TITLE
Check consistency of filetypes DB and themes via Travis

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/vivid#19]
Probably by simply doing sth like
```bash
for theme in ...; do
  cargo run -- generate "$theme" # ...
done
```

**Comment by polyzen** [comment]
Going to need sorting or something for deterministic generation.

**Comment by sharkdp** [comment]
In a first step, we don't even need to check the output. We could just run this and make sure that we get exit code 0 for each of the themes. This would make sure that we do not have any YAML Syntax errors and no consistency errors in the themes (e.g. missing categories) and filetypes DB (e.g. duplicate file extensions).

**Comment by polyzen** [comment]
https://github.com/adrienverge/yamllint
