### ISSUE TITLE
Simplify installation process for non-Ubuntu distributions

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/vivid#20]

**Comment by breed808** [comment]
What do you have in mind for a simplified installation process? Native package format (RPM for Fedora/openSUSE, AUR entry for Arch, etc)?

**Comment by sharkdp** [comment]
> What do you have in mind for a simplified installation process? Native package format (RPM for Fedora/openSUSE, AUR entry for Arch, etc)?

Yes - exactly. We already have packages for Debian-based distributions and for Arch Linux, but it would be great to support other distributions as well. The installation is a bit more involved because we need to copy `filetypes.yml` and the themes to the correct locations (see e.g. https://github.com/sharkdp/vivid/blob/a4269db334b4dc4207f876afa26f5e5650fdff53/ci/before_deploy.bash#L31-L35).

**Comment by polyzen** [comment]
> > What do you have in mind for a simplified installation process? Native package format (RPM for Fedora/openSUSE, AUR entry for Arch, etc)?
> 
> Yes - exactly. We already have packages for Debian-based distributions and for Arch Linux, but it would be great to support other distributions as well. The installation is a bit more involved because we need to copy `filetypes.yml` and the themes to the correct locations (see e.g.
> 
> [vivid/ci/before_deploy.bash](https://github.com/sharkdp/vivid/blob/a4269db334b4dc4207f876afa26f5e5650fdff53/ci/before_deploy.bash#L31-L35)
> 
> Lines 31 to 35 in [a4269db](/sharkdp/vivid/commit/a4269db334b4dc4207f876afa26f5e5650fdff53)
>  # filetype database and themes 
>  mkdir -p "$tempdir/$package_name/share/vivid" 
>  mkdir -p "$tempdir/$package_name/share/vivid/themes" 
>  cp config/filetypes.yml "$tempdir/$package_name/share/vivid" 
>  cp themes/*.yml "$tempdir/$package_name/share/vivid/themes" 
> ).

That could be shortened to:
```
install -Dm644 -t "$tempdir"/$package_name/share/vivid config/filetypes.yml
install -Dm644 -t "$tempdir"/$package_name/share/vivid/themes themes/*
```

**Comment by breed808** [comment]
I've [packaged vivid](https://build.opensuse.org/package/show/home:breed808/vivid) for my own personal use which may be helpful here.
Of note is the use of `cargo vendor` to statically include cargo dependencies, as the openSUSE build system does not allow network requests while building.

**Comment by sharkdp** [comment]
This is now much easier due to #43 by @LordFlashmeow.
