### ISSUE TITLE
Run vivid on MacOS

### ISSUE THREAD

**Issue by erusev** [sharkdp/vivid#25]
Is it possible to run vivid on MacOS?

I installed `vivid` with `cargo`, copied `filetypes.yml` to `.config/vivid` to avoid the `Error: Could not find filetypes database` but then adding `export LS_COLORS="$(vivid generate molokai)"` to `.zshrc` did nothing, which made me research a bit more and I found out that MacOS uses `LSCOLORS` and that it doesn't work the same as `LS_COLORS` so I guess this means that `vivid` won't run on MacOS, but I thought I should ask.

**Comment by sharkdp** [comment]
Thank you for the feedback.

As you found out, `vivid` should work just fine on MacOS. If you use `fd` or `tree` (which support `LS_COLORS`), you should see the colors generated by `vivid`.

If you use `ls`, the colors will not work. As you pointed out, MacOS uses the BSD version of `ls` which uses `LSCOLORS`. This variable has a different format that is not very powerful (there is no way to colorize files by extension). However, I think you could use the GNU coreutils version of `ls` and `LS_COLORS` should work just fine. I'm not a MacOS user, but I think you can do something like
```
brew install coreutils
alias ls=gls
```

**Comment by erusev** [comment]
Thanks so much! 

Unfortunately, `fd` is also without colors. Perhaps, I didn't install `vivid` right.

The `README.md` says:

> Make sure that you install the contents of the `share/vivid` folder at `/usr/share/vivid` or at `$HOME/.config/vivid`.

But I didn't find a `share` folder so I created `.config/vivid` and I copied `filetypes.yml` there in attempt to avoid the `Error: Could not find filetypes database`. Perhaps, this was not the correct way to do this and that's why it doesn't work now.

**Comment by sharkdp** [comment]
I have recently added support for 24-bit colors in `fd`, but so far, fd-7.2.0 can only display 8-bit colors. You can either install `fd` from `master`, wait for the next version, or use `vivid` in 8-bit mode (see README).

**Comment by erusev** [comment]
Setting vivid to 8-bit mode worked!

Thanks so much for your help and for your work on these CLI tools - they made me excited about command line :)

**Comment by sharkdp** [comment]
Cool! Thank you for the feedback.

We should probably add a section concerning MacOS to the README.

**Comment by sharkdp** [comment]
If someone is familiar with Homebrew and could help in creating a Formula for `vivid`, that would be awesome.

**Comment by zachvalenta** [comment]
`fd` and `bat` are both available in Homebrew. Would it be possible to reuse work from those projects in order to get `vivid` a Formula?

**Comment by twome** [comment]
on macOS, `vivid` should instruct the user to copy "themes/" and "filetypes.yml" to `~/.config/vivid`, as for me, specifying the "filetypes.yml" location via the CL arguments flag gave the same error as OP. Thanks for the program, it's super handy!

**Comment by gibfahn** [comment]
Raised a PR for this: https://github.com/Homebrew/homebrew-core/pull/55962

IDK if the PR will land, but you can use this directly with:

```shell
brew install https://raw.githubusercontent.com/gibfahn/homebrew-core/vivid/Formula/vivid.rb
```

**Comment by sharkdp** [comment]
Sure, let's check `XDG_CONFIG_PATH`.

**Comment by NightMachinary** [comment]
@sharkdp Can't the assets be bundled with the cargo install, so that things just work crossplatformly using cargo? One would have to pay the compilation costs, but I gladly pay them when I can reuse my config crossplatformly.

**Comment by sharkdp** [comment]
> @sharkdp Can't the assets be bundled with the cargo install, so that things just work crossplatformly using cargo? One would have to pay the compilation costs, but I gladly pay them when I can reuse my config crossplatformly.

I don't know, but I would support that change, if that's possible.



> BTW it would be really nice if the install directory was overridable (it currently doesn't even use `XDG_CONFIG_HOME`). There's `$VIVID_DATABASE` but that only works for the database, not for the themes. Would be nice if you could just set `VIVID_CONFIG=/path/to/vivid` and use that directly, would also make brew installation easier.

@gibfahn #40 has been merged now. Do you think we need anything else? I see that the PR for homebrew has been closed. Maybe someone else wants to pick this up and get it finished?

**Comment by gibfahn** [comment]
Yeah, sorry, out of time right now. If the issues in the previous PR can be fixed, a new PR should be "straightforward".

**Comment by LordFlashmeow** [comment]
I'm taking a look at it now, I'll see what's possible.

**Comment by LordFlashmeow** [comment]
I see two options for dealing with homebrew: adding the files to the executable, or adding a compile-time config setting (like `--prefix` for `make`) for where the files are stored.

For embedding the theme and config files, we can use `include_bytes!` or [rust-embed](https://github.com/pyros2097/rust-embed).

For a compile time config settings, we would use `option_env!` and then add that to the list of directories to search for config files. This would make the Homebrew formula pretty simple, since we can point vivid to `#{prefix}/share` (which would be `/usr/local/Cellar/vivid/0.6/share`) and copy the files to there. However, this doesn't simplify installation from cargo, since the user still needs to download the config files to somewhere.

Embedding makes more sense to me, since it means new users don't need to download the config files unless they want to make changes to them.

I'll draft a PR for embedding soon.

**Comment by SimplyDanny** [comment]
In the meantime, I have fixed the remarks in the [PR](https://github.com/Homebrew/homebrew-core/pull/55962) trying to add the vivid formula to Homebrew. It works with version 0.5.0. A caveat asks the user to link the assets to `~/.config/vivid` for now. You can find it [here](https://github.com/SimplyDanny/homebrew-core/commit/209d191e1e5fe2f7b9d4c777e36a647fd8723c92).

Does it make sense to open a new PR in Homebrew for the current state (vivid 0.5.0 without embedded assets) or shall we wait for 0.6.0 with @LordFlashmeow's proposal implemented?

**Comment by LordFlashmeow** [comment]
I'm pretty sure that the Homebrew folks won't accept the formula if users need to link the files manually (for a couple of reasons)

**Comment by sharkdp** [comment]
> I see two options

Couldn't we simply search other paths if we detect that we run on macOS? What would be the standard path to put such files? I was hoping it would be  `/usr/share/vivid` as well.

**Comment by SimplyDanny** [comment]
> What would be the standard path to put such files? I was hoping it would be `/usr/share/vivid` as well.

For software installed by Homebrew it would be `$(brew --prefix)/share/vivid` which is typically but not necessarily `/usr/local/share/vivid`.

**Comment by LordFlashmeow** [comment]
If we embed the files, I think it would be acceptable to only search for the files in XDG_CONFIG_HOME (by default ~/.config/vivid). I don’t think there’s a huge number of people who use custom themes, and I think that’s a safe consistent place to put them.

**Comment by SimplyDanny** [comment]
Well, I'm not an expert, but [people on the internet](https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x/5084892#comment67156521_3373948) suggest that `XDG_CONFIG_HOME` is rather `~/Library/Application Support` or `~/Library/Preferences` on macOS.

With that in mind, I think it is reasonable to search in `$XDG_CONFIG_HOME`, then in `~/.config/vivid` and if nothing is found there fall back to the embedded assets.

**Comment by LordFlashmeow** [comment]
Yeah, but Homebrew people prefer the Linux way, so they like using `~/.config` by default (but using`XDG_CONFIG_HOME` if it is defined). When I looked, I couldn't find a single app installed via homebrew that put its files in `~/Library/Application Support` or ~/Library/Preferences`.

**Comment by sharkdp** [comment]
> If we embed the files, I think it would be acceptable to only search for the files in XDG_CONFIG_HOME (by default ~/.config/vivid). I don’t think there’s a huge number of people who use custom themes, and I think that’s a safe consistent place to put them.

Agreed. But I like the fact that users can use the filetype database (or themes) in `/usr/…` as a starting point for customizations.

**Comment by sharkdp** [comment]
#43 has been merged and I have released 0.6.0. This should hopefully make packaging much easier. Thank you, @LordFlashmeow!

**Comment by SimplyDanny** [comment]
I opened another [PR](https://github.com/Homebrew/homebrew-core/pull/61447) adding vivid 0.6.0 to Homebrew.

**Comment by sharkdp** [comment]
This can be closed, right?

Maybe we can add install instructions for MacOS/homebrew to the README?

**Comment by zachvalenta** [comment]
> Maybe we can add install instructions for MacOS/homebrew to the README?

I took a swing at it here https://github.com/sharkdp/vivid/pull/52
