### ISSUE TITLE
Create a macOS category for unimportant files

### ISSUE THREAD

**Issue by gseidler** [sharkdp/vivid#32]
MacOS creates a few files on its directory structure that are generally not meant to be edited (or seen) by regular users. They are usually markers for encoding/translation or settings for window position and configurations. I configure them as unimportant so they don't stand out so much when listing all files in a directory. So far I included on my personal filetypes.yml:
.CFUserTextEncoding
.DS_Store
.localized

**Comment by sharkdp** [comment]
Sounds good!

Happy to merge these in if you want to submit a PR.
