### ISSUE TITLE
vivid generate ayu fails with "Error: Theme file is empty"

### ISSUE THREAD

**Issue by hferreiro** [sharkdp/vivid#45]
With no configuration, vivid is able to generate colors for every theme file but ayu.

**Comment by sharkdp** [comment]
I can not reproduce this. Are you sure that you do not have a left-over `themes` folder somewhere in `/usr/share/vivid/` or `~/.config/vivid`?

**Comment by hferreiro** [comment]
I'm sorry, I had a file named ayu 🤦

**Comment by sharkdp** [comment]
ahh - that's an unfortunate coincidence :smile:
