### ISSUE TITLE
Zinit plugin permission denied

### ISSUE THREAD

**Issue by mortezadadgar** [sharkdp/vivid#50]
Installed vivid as a plugin like this
```
zinit ice as'command' from'gh-r' bpick'*unknown-linux-gnu*' mv'vivid* -> vivid' atload'export LS_COLORS="$(vivid generate molokai)"'
zinit light sharkdp/vivid
```
it throw out the permission denied error for every zsh initialization
(eval):1: permission denied: vivid

I see vivid binary file need to be installed as root group but why it's a most for a program that changes the colors of tools output

**Comment by sharkdp** [comment]
I don't know what `zinit ice` and `zinit light` do. `vivid` has nothing to do with `zsh`. Where did you get these commands from?

**Comment by mortezadadgar** [comment]
`zinit ice` command download the linux package from github release page and rename it to vivid, then 'zinit light' load the vivid as a command
I know vivid has nothing to do with zsh but zinit can be used to install many packages like bat, fd, fzf, etc; the actual question here is why vivid requires root permission to apply LS_COLORS

**Comment by sharkdp** [comment]
It does not require root permissions. Maybe the executable bit is not set (`chmod +x vivid`)?

**Comment by mortezadadgar** [comment]
It's
zinit vivid-> -rwxr-xr-x 1 morteza morteza 1.1M Sep 20 21:02 vivid
/usr/bin/vivid-> -rwxr-xr-x 1 root root 987K Sep 21 01:51 /usr/bin/vivid

**Comment by sharkdp** [comment]
I'm sorry, but this has nothing to do with `vivid`. I'd be glad to help, but I don't know `zinit`. Could you please ask your question in the `zinit` repo?
