### ISSUE TITLE
[Request] Windows binary release

### ISSUE THREAD

**Issue by chawyehsu** [sharkdp/vivid#53]
Could you please provide the Windows binary as well while publishing releases?

Of cause, I could build it myself. But I think we can have the official binary release for Windows, so that package managers like [Scoop](https://scoop.sh) can create package manifest based on it.

**Comment by sharkdp** [comment]
We will have to migrate our CI/CD system to Github Actions soon. When we do that, we can try to add Windows binaries.

**Comment by sharkdp** [comment]
Windows builds are now available: https://github.com/sharkdp/vivid/releases/tag/v0.8.0
