### ISSUE TITLE
the color theme didn't get affected after export for ls command but works for tree command

### ISSUE THREAD

**Issue by monacv** [sharkdp/vivid#54]
after I used the following command:

`export LS_COLORS="$(vivid generate molokai)"`

the color theme didn't get affected for ls command:
![Screenshot from 2020-12-29 18-02-46](https://user-images.githubusercontent.com/76495162/103319520-2cfa7900-4a00-11eb-87d9-94be15aab7d3.png)

and

![Screenshot from 2020-12-29 18-06-09](https://user-images.githubusercontent.com/76495162/103319670-97abb480-4a00-11eb-9178-d0bfab37d74f.png)

**Comment by sharkdp** [comment]
Thank you for reporting this.

Could you please tell us:
- which terminal you are using? Does it support 24-bit colors? Otherwise, please try https://github.com/sharkdp/vivid#terminals-without-true-color-support
- which version of `ls` you are using? Is it the GNU coreutils version? Or the BSD version? In the latter case, consider installing the GNU version: https://github.com/sharkdp/vivid#on-macos

**Comment by monacv** [comment]
```
alias ls='ls -ltra -h'


$ echo $TERM
xterm-256color

$ echo $SHELL
/bin/bash

$ echo $$
229340
$  cat /proc/229340/comm 
bash
```

**Comment by sharkdp** [comment]
`$TERM` doesn't really tell enough. Is `$COLORTERM` set? What terminal are you using? Gnome Terminal?

Also, could you please try the other suggestions and show the version of `ls`?
```
ls --version
```

**Comment by monacv** [comment]
```
$ echo $COLORTERM
truecolor
2420/31772MB
[819478:3298 0:1555] 04:51:49 Mon Jan 04 [mona@goku:pts/4 +1] ~/research/code/DJ-RN/pointnet
$ ls --version
ls (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.

```

**Comment by sharkdp** [comment]
> What terminal are you using? Gnome Terminal?



>     * please try https://github.com/sharkdp/vivid#terminals-without-true-color-support

**Comment by sharkdp** [comment]
> `alias ls='ls -ltra -h'`

Oh, actually that's the problem. You need to add `--color=auto` to see ls-colors!

**Comment by monacv** [comment]
I added that in my alias in ~/.bashrc

do you expect the coloring to be like below?

![Screenshot from 2021-01-06 15-11-58](https://user-images.githubusercontent.com/76495162/103815567-8894ba00-5031-11eb-8005-8749c916e105.png)

**Comment by monacv** [comment]
nvm forgot the export term
![Screenshot from 2021-01-06 15-12-53](https://user-images.githubusercontent.com/76495162/103815668-b417a480-5031-11eb-8c3a-3273e2610791.png)
