### ISSUE TITLE
Upload .deb to Debian

### ISSUE THREAD

**Issue by savchenko** [sharkdp/vivid#55]
As you already have a functioning *.deb, would you consider uploading it via https://mentors.debian.net?
Would be great to have `vivid` available straight from the Debian repositories and there is currently no package with the same name.

**Comment by sharkdp** [comment]
Thank you for the feedback.

If someone wants to do this, please go ahead. But I'm not personally going to invest time in maintaining the Debian packages. I'm not even using a Debian-based distribution myself.

**Comment by savchenko** [comment]
Well, let's try: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=981375

**Comment by sharkdp** [comment]
Awesome, thank you!

**Comment by sharkdp** [comment]
closing this for now
