### ISSUE TITLE
Output is not deterministic 

### ISSUE THREAD

**Issue by neersighted** [sharkdp/vivid#63]
The output of `vivid generate` is not deterministic -- subsequent runs differ. Scenarios where the output of Vivid is cached (or used in an idempotent script) could be improved by making the output deterministic.

**Comment by sharkdp** [comment]
Thank you for reporting this.

Do you mean: the output is not deterministic?

If so, you are absolutely right. I did not know that. It's probably due to the use of hash maps. I agree that this would be worth fixing.

That's probably even a bug, because the order of entries in `LS_COLORS` matters in case of conflicts:
```
touch test.txt
LS_COLORS='*.txt=0;31:*.txt=0;33' ls --color
LS_COLORS='*.txt=0;33:*.txt=0;31' ls --color
```

**Comment by neersighted** [comment]
Err, yes, I crossed a wire there. Non-deterministic makes idempotent use of `vivid` in scripts difficult.

The use of HashMaps makes sense -- an ordered collection would probably easily fix this (but then, the real question becomes what the 'correct' order is).

**Comment by sharkdp** [comment]
> Err, yes, I crossed a wire there. Non-deterministic results make idempotent use of `vivid` in scripts difficult.

:+1: 



> The use of HashMaps makes sense -- an ordered collection would probably easily fix this 

Yes. (Maybe it's also the YAML deserialization.)

> but then, the real question becomes what the 'correct' order is

I think we shouldn't care too much about this question and rather implement a conflict-detection, if that is needed.

If there are two patterns like `*.txt` and `*CMakeLists.txt` (which needs the glob star in the beginning, unfortunately), we should make sure that the second one has precedence in case there is a file called `CMakeLists.txt`. But *I think* this is already guaranteed by the `LS_COLORS` "format" (or the reference implementation in `ls`) - but this should be checked again.

**Comment by tavianator** [comment]
> If there are two patterns like *.txt and *CMakeLists.txt (which needs the glob star in the beginning, unfortunately), we should make sure that the second one has precedence in case there is a file called CMakeLists.txt. But I think this is already guaranteed by the LS_COLORS "format" (or the reference implementation in ls) - but this should be checked again.

Not really, `ls` is strictly last-match-wins:

![image](https://user-images.githubusercontent.com/1692591/173137714-1941cf6e-012d-492a-8ff8-5dc4f8e57f10.png)

Vivid should probably sort the suffixes from shortest to longest so that the most specific one will match.

**Comment by tavianator** [comment]
> Vivid should probably sort the suffixes from shortest to longest so that the most specific one will match.

Oh, it already does: https://github.com/sharkdp/vivid/blob/700c9a6c15e949f6fa5f1ec1c8aa20bdf018f4d6/src/main.rs#L193-L194
