### ISSUE TITLE
cargo install missing lava theme

### ISSUE THREAD

**Issue by Gary-Armstrong** [sharkdp/vivid#68]
Files end up in `~/.cargo/registry/src/github.com-1ecc6299db9ec823/vivid-0.7.0/themes` and are
```ayu.yml
jellybeans.yml
molokai.yml
one-dark.yml
one-light.yml
snazzy.yml
solarized-dark.yml
solarized-light.yml
```
I can work around it but seems like github and crates.io do not agree.

**Comment by sharkdp** [comment]
I have not released a new version since the lava theme was added...

**Comment by Gary-Armstrong** [comment]
Thanks for the response :)
