### ISSUE TITLE
Builds for armv6 and armv7

### ISSUE THREAD

**Issue by mafrosis** [sharkdp/vivid#74]
Hi, it would be great if `vivid` was built for arm, as part of this project.

I'm not au fait with travis config and Debian packaging, so I solved my immediate problem here:
https://github.com/mafrosis/vivid/commit/7ebaeb770a18935e2d18e0ab25046e2e9899e1a7

And for future googlers, there are binaries available here:
https://github.com/mafrosis/vivid/releases/tag/v0.7.0

**Comment by sharkdp** [comment]
Yes thank. We need to move to GitHub actions at some point (like with some of my other projects). We can add these platforms in this step.

**Comment by danieltaylor** [comment]
I packaged them into debs in case anyone finds that helpful.  The armv6 one looks like it's compiled for armhf, so it might not work on all armv6 devices, but should work on certain devices like Raspberry Pis (if I'm understanding that part correctly).

[vivid_0.7.0_armv6.deb.tar.gz](https://github.com/sharkdp/vivid/files/7759904/vivid_0.7.0_armv6.deb.tar.gz)
[vivid_0.7.0_armv7.deb.tar.gz](https://github.com/sharkdp/vivid/files/7759907/vivid_0.7.0_armv7.deb.tar.gz)

**Comment by sharkdp** [comment]
ARM builds are now available: https://github.com/sharkdp/vivid/releases/tag/v0.8.0
