### ISSUE TITLE
Cannot generate gruvbox-light, gruvbox-dark

### ISSUE THREAD

**Issue by zane** [sharkdp/vivid#84]
## Reproduction steps

```
❯ vivid generate gruvbox-light
```
```
❯ vivid generate gruvbox-dark
```

## Expected result

vivid outputs a theme string.

## Actual result

```
❯ vivid generate gruvbox-light
Error: Could not find style for category 'core.reset_to_normal'
```
```
❯ vivid generate gruvbox-dark
Error: Could not find style for category 'core.setuid'
```

**Comment by sharkdp** [comment]
Are you using v0.8?

**Comment by zane** [comment]
Yes.
```
❯ vivid --version
vivid 0.8.0
```

**Comment by sharkdp** [comment]
Hm. Any chance you happen to have a user-custom filetype database or theme set up?

https://github.com/sharkdp/vivid#customization

Or maybe some leftover files from a previous installation in `/usr/share/vivid`?

**Comment by zane** [comment]
Sure do. Thanks, and sorry for the noise!

**Comment by sharkdp** [comment]
No worries. Quite the contrary. Thank you for reporting this. I think that should have been handled better by vivid. We should probably introduce a `version` field in the themes/database files to warn users of non-compatible old versions of these files in the future.
